= Jenkins Configuration-as-Code

Rationale...  https://jenkins.io/blog/2018/08/23/speaker-blog-casc-part-1/


== Configuration As Code (CasC) Plugin

Config samples taken from https://github.com/jenkinsci/configuration-as-code-plugin/tree/master/demos

Dockerfile: Dockerfile used to build image

plugins.txt: jenkins plugins installed to the docker image


=== Usage

Update Jenkins image to latest (assuming the default _lts_ tag) :

`docker rmi jenkins\jenkins:lts`

Build image:

`docker build -t docker-jenkins-casc .`


Run image:

`docker run --rm --name jenkinsdev -p 8080:8080 -p 50000:50000 docker-jenkins-casc`


Run image binding to docker sock (insecure!):

`docker run --rm --user root --privileged --name jenkinsdev -p 8080:8080 -p 50000:50000  -v /var/run/docker.sock:/var/run/docker.sock docker-jenkins-casc`

Run Image with environment variables:

`docker run --rm --name jenkinsdev -p 8080:8080 -p 50000:50000 -e admin_user='bob' -e admin_pwd='passwd' -e github_user=billy -egithub_pwd=passwd111 -e github-repo-owner=billy docker-jenkins-casc`

This is not secure, it's better to use Docker and Kubernetes secrets for the passwords.

The environment variables are:

- admin_user - the Jenkins admin user name
- admin_pwd - the Jenkins admin password
- github_user - the user account used by the Jenkins "Seed Job" to perform git/github commands
- github_pwd - the git hub account password
- github-repo-owner - the github owner/organisation name e.g. `https://github.com/{orgName}`

=== Volumes

Volume mapping used to contain the CasC plugin config files

Copy to Docker volume via a dummy container (from https://github.com/moby/moby/issues/25245):

 docker container create --name dummy -v jenkins_casc:/root hello-world
 docker cp casc_configs/jenkins.yaml dummy:/root/jenkins.yaml
 docker rm dummy

==== Useful Links

https://github.com/trion-development/docker-jenkins-docker-client


Use of certs:

https://docs.docker.com/engine/security/https/#secure-by-default

=== CasC Configuration

Configures a Github organisation project.  Only the Github credentials need adding manually to do this inside the Jenkins UI:
. Seed Job -> Configuration
. Projects -> Credentials (to Seed Job scope)
. Credentials -> Github Username and Password (SSH Key is not supported)
. Credentials Drop down select the newly entered credentials.
. Save and the project will be automatically scanned.

Note anonymous access will work for public but Github throttles such accesses making it almost unusable in practice.