= Jenkins Configuration-as-Code

The general rationale is described here:  https://jenkins.io/blog/2018/08/23/speaker-blog-casc-part-1/

== Features

- Zero manual configuration.  Once the Docker container is run it will auto-discover repos and start building.
- Intended for use by a single github user or github organisation account.
- Runs as a Docker container with sensitive data passed as either environment variables or as Docker/Kubernetes secrets
- Jobs are automatically created by scanning the github organisation for repos/branches with a `Jenkinsfile` in the root of the repo.
- Additional plugins can be added by adding values to plugins.txt and configuration added to `casc_configs/jenkins.yaml`
- It's assumed, but not mandated, that specific toolchains will be handled by the Jenkinsfile possibly within Docker containers.

== Implementation

The implementation relies on the Configuration As Code (CasC) Plugin and Github Organisation support.  CASC config samples are taken from https://github.com/jenkinsci/configuration-as-code-plugin/tree/master/demos

=== Building the Docker Image

Update Jenkins image to latest (assuming the default _lts_ tag) :

`docker rmi jenkins\jenkins:lts`

Build image:

`docker build -t docker-jenkins-casc .`

=== Running the Docker Container

Basic usage.  This assumes the admin user, github user and repo owner environment variables are set elsewhere or specified as secrets.

`docker run --rm --name jenkinsdev -p 8080:8080 -p 50000:50000 docker-jenkins-casc`


To build Docker images within a Docker container need access to the Docker host's Docker daemon.  Running the container as `root` is the simplest but least secure.

`docker run --rm --user root --privileged --name jenkinsdev -p 8080:8080 -p 50000:50000  -v /var/run/docker.sock:/var/run/docker.sock docker-jenkins-casc`

Run container with environment variables on the command line.  This isn't secure as passwords are in clear text.  It's better to use Docker and Kubernetes secrets for the passwords.

`docker run --rm --name jenkinsdev -p 8080:8080 -p 50000:50000 -e admin_user='bob' -e admin_pwd='passwd' -e github_user=billy -egithub_pwd=passwd111 -e github-repo-owner=billy docker-jenkins-casc`

The environment variables are:

- admin_user - the Jenkins admin user name
- admin_pwd - the Jenkins admin password
- github_user - the user account used by the Jenkins "Seed Job" to perform git/github commands
- github_pwd - the git hub account password
- github-repo-owner - the github owner/organisation name e.g. `https://github.com/{orgName}`

==== Useful Links

- https://github.com/trion-development/docker-jenkins-docker-client
- https://javadoc.jenkins.io/plugin/

Use of certs:

https://docs.docker.com/engine/security/https/#secure-by-default

== Known Limitations

. In theory with appropriate configuration, Github will notify about the creation and removal of branches.  5 minute polling is also hardcoded in the CASC config file `jenkins.yaml`
. Repo selection is hardcoded to all branches - see the regexs and strategy Id in `jenkins.yaml`
. Build slaves are not configured as this tends to be highly project specific.
. Building Docker images without running as root needs exploring if needed.

