= Jenkins Configuration-as-Code

== Configuration As Code (CasC) Plugin

Config samples taken from https://github.com/jenkinsci/configuration-as-code-plugin/tree/master/demos

Dockerfile: Dockerfile used to build image

plugins.txt: jenkins plugins installed to the docker image


=== Usage

Update Jenkins image to latest (assuming the default _lts_ tag) :

`docker rmi jenkins\jenkins:lts`

Build image:

`docker build -t docker-jenkins-casc .`


Run image:

`docker run --rm --name jenkinsdev -p 8080:8080 -p 50000:50000 docker-jenkins-casc`


Run image binding to docker sock (insecure!):

`docker run --rm --user root --privileged --name jenkinsdev -p 8080:8080 -p 50000:50000  -v /var/run/docker.sock:/var/run/docker.sock docker-jenkins-casc`

=== Volumes

Volume mapping used to contain the CasC plugin config files

Copy to Docker volume via a dummy container (from https://github.com/moby/moby/issues/25245):

 docker container create --name dummy -v jenkins_casc:/root hello-world
 docker cp casc_configs/jenkins.yaml dummy:/root/jenkins.yaml
 docker rm dummy

==== Useful Links

https://github.com/trion-development/docker-jenkins-docker-client


Use of certs:

https://docs.docker.com/engine/security/https/#secure-by-default

=== CasC Configuration

Configures a Github organisation project.  Only the Github credentials need adding manually to do this inside the Jenkins UI:
. Seed Job -> Configuration
. Projects -> Credentials (to Seed Job scope)
. Credentials -> Github Username and Password (SSH Key is not supported)
. Credentials Drop down select the newly entered credentials.
. Save and the project will be automatically scanned.

Note anonymous access will work for public but Github throttles such accesses making it almost unusable in practice.