jenkins:
  systemMessage: "Jenkins configured automatically by Jenkins Configuration as Code Plugin\n\n"
  numExecutors: 5
  scmCheckoutRetryCount: 2
  mode: NORMAL


tool:
  git:
    installations:
      - name: git
        home: git
#  gradle:
#    installations:
#      - name: gradle
#        home: ~/gradle

security:
    remotingCLI:
        enabled: false

unclassified:
  location:
    url: "http://localhost:8080/jenkins/"
  githubpluginconfig:
    configs:
    - name: "InHouse GitHub EE"
      apiUrl: "https://github.domain.local/api/v3"
      credentialsId: "[GitHubEEUser]"
      manageHooks: true

# Copied from https://github.com/jenkinsci/configuration-as-code-plugin/tree/master/demos/jobs
jobs:
  - script: >
      organizationFolder('Github Organization Folder') {
        description("Github org folder")
        displayName('Seed Job')

        triggers {
          cron('@daily')
        }
        
        // "Projects"
        organizations {

          //Possible solutions: repoOwner(), apiUri(), buildForkPRHead(), buildForkPRMerge(), buildOriginBranch(), buildOriginBranchWithPR(), buildOriginPRHead(), buildOriginPRMerge(), credentialsId(), excludes(), includes(), pattern(), scanCredentialsId(), traits()

          github {
            apiUri("https://api.github.com/")
            repoOwner("cpaulcox")
            //credentialsId("bitbucket-http")

            // "Traits" ("Behaviours" in the GUI) that are "declarative-compatible" 
            traits {        
              webhookRegistrationTrait {
                mode('ITEM')
              } 
              submoduleOptionTrait {
                extension {
                  disableSubmodules(false)
                  recursiveSubmodules(true)
                  trackingSubmodules(false)
                  reference(null)
                  timeout(null)
                  parentCredentials(true)
                }
              }
            }
          }

        }

        // "Project Recognizers"
        projectFactories {
            workflowMultiBranchProjectFactory {
                scriptPath 'Jenkinsfile'
            }
        }

        // "Orphaned Item Strategy"
        orphanedItemStrategy {
          discardOldItems {
            daysToKeep(-1)
            numToKeep(-1)
          }
        }
      }
      
