jenkins:
  systemMessage: "Jenkins configured automatically by Jenkins Configuration as Code Plugin\n\n"
  numExecutors: 5
  scmCheckoutRetryCount: 2
  mode: NORMAL

  agentProtocols: 
    - "JNLP4-connect" 
  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: demoAdmin
         password: ${adminpw:-passw0rd}  # TODO
  authorizationStrategy:
    globalMatrix:
      grantedPermissions:
        - "Overall/Read:anonymous"
        - "Job/Read:anonymous"
        - "View/Read:anonymous"
        - "Overall/Administer:authenticated"
  crumbIssuer: "standard"

credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword: 
              scope:    SYSTEM
              id:       github-user
              username: ReleasePraqma
              password: password1 #${github}  # TODO
          # - basicSSHUserPrivateKey: 
          #     scope: SYSTEM
          #     id: agent-private-key
          #     username: agentuser
          #     passphrase:  ""
          #     description: "ssh private key used to connect ssh slaves"
          #     privateKeySource:
          #       directEntry: # The key 'agent_private_key' resolved from a docker secret defined in docker-compose.yml          
          #     privateKey: ${agent_private_key}

tool:
  git:
    installations:
      - name: git
        home: git
# Not needed as builds are done within Docker containers with specific toolchains
#  gradle:
#    installations:
#      - name: gradle
#        home: ~/gradle

security:
    remotingCLI:
        enabled: false

unclassified:
  location:
    url: "http://localhost:8080/jenkins/"
  githubpluginconfig:
    configs:
    - name: "InHouse GitHub EE"
      apiUrl: "https://github.domain.local/api/v3"
      credentialsId: "[GitHubEEUser]"
      manageHooks: true

# Copied from https://github.com/jenkinsci/configuration-as-code-plugin/tree/master/demos/jobs
jobs:
  - script: >
      organizationFolder('Github Organization Folder') {
        description("Github org folder")
        displayName('Seed Job')
        triggers {
          cron('@daily')
        }
        
        configure { node ->
        node / navigators / 'org.jenkinsci.plugins.github_branch_source.GitHubSCMNavigator' {
          repoOwner "cpaulcox"
          apiUri "https://api.github.com/"
        }
        def traits = node / navigators / 'org.jenkinsci.plugins.github_branch_source.GitHubSCMNavigator' / traits
        //traits << 'jenkins.scm.impl.trait.RegexSCMSourceFilterTrait' {
        //    regex('.*')   
        //}
        traits << 'org.jenkinsci.plugins.github_branch_source.BranchDiscoveryTrait' {
            strategyId('1')   
        }
        traits << 'jenkins.scm.impl.trait.RegexSCMHeadFilterTrait' {
            regex('.*')   
        }

        }

        // "Project Recognizers"
        projectFactories {
            workflowMultiBranchProjectFactory {
                scriptPath 'Jenkinsfile'
            }
        }

        // "Orphaned Item Strategy"
        orphanedItemStrategy {
          discardOldItems {
            daysToKeep(-1)
            numToKeep(-1)
          }
        }
      }
      
