jenkins:
  systemMessage: "Jenkins configured automatically by Jenkins Configuration as Code Plugin\n\n"
  numExecutors: 5
  scmCheckoutRetryCount: 2
  mode: NORMAL


tool:
  git:
    installations:
      - name: git
        home: git
#  gradle:
#    installations:
#      - name: gradle
#        home: ~/gradle

security:
    remotingCLI:
        enabled: false

unclassified:
  location:
    url: "http://localhost:8080/jenkins/"
  githubpluginconfig:
    configs:
    - name: "InHouse GitHub EE"
      apiUrl: "https://github.domain.local/api/v3"
      credentialsId: "[GitHubEEUser]"
      manageHooks: true

# Copied from https://github.com/jenkinsci/configuration-as-code-plugin/tree/master/demos/jobs
jobs:
  - script: >
      organizationFolder('Github Organization Folder') {
        description("Github org folder")
        displayName('Seed Job')

        triggers {
          cron('@daily')
        }
        
        configure { node ->
        def traits = node / navigators / 'com.cloudbees.jenkins.plugins.github_branch_source.GitHubSCMNavigator' / traits
        //traits << 'jenkins.scm.impl.trait.RegexSCMSourceFilterTrait' {
        //    regex('.*')   
        //}
        traits << 'com.cloudbees.jenkins.plugins.github_branch_source.BranchDiscoveryTrait' {
            strategyId('1')   
        }
        traits << 'jenkins.scm.impl.trait.RegexSCMHeadFilterTrait' {
            regex('.*')   
        }

        }

        // "Projects"
        organizations {

          //Possible solutions: repoOwner(), apiUri(), buildForkPRHead(), buildForkPRMerge(), buildOriginBranch(), buildOriginBranchWithPR(), buildOriginPRHead(), buildOriginPRMerge(), credentialsId(), excludes(), includes(), pattern(), scanCredentialsId(), traits()
          // See https://jenkinsci.github.io/job-dsl-plugin/#method/javaposse.jobdsl.dsl.helpers.workflow.BranchSourcesContext.github

          github {
            apiUri("https://api.github.com/")
            repoOwner("cpaulcox")
          }
        }

        // "Project Recognizers"
        projectFactories {
            workflowMultiBranchProjectFactory {
                scriptPath 'Jenkinsfile'
            }
        }

        // "Orphaned Item Strategy"
        orphanedItemStrategy {
          discardOldItems {
            daysToKeep(-1)
            numToKeep(-1)
          }
        }
      }
      
