= Ruby & Sinatra

* Base image for Sinatra based apps
* Inside a proxied network pass to Docker the proxy environment variables otherwise Gems won't build: `sudo docker build --build-arg http_proxy=$http_proxy --build-arg https_proxy=$https_proxy .`
* The base image installs Sinatra and its dependencies and sets up and application home - `sudo docker build -t sample/sinatra -f DockerfileSinatra .`
* The application image copies ruby source files into the APP_HOME directory, runs the application and labels the build. `sudo docker build -t sample/hello-sinatra -f DockerfileHelloSinatra .`


== To Run

Run as a daemon with a name to simplify stopping.  `--rm` is less useful and hard to stop the container without a name or by ctrl+c.

`docker run --name helloSinatra -d sample/hello-sinatra`

Use `docker inspect helloSinatra | grep IP` to get the container IP Address which can be used on port 8080 to access the site or run using -p8080:8080 to access via the host's IP (or _localhost_ if running locally).


Sample script:

----

docker run --name helloSinatra -p 8080:8080 -d sample/hello-sinatra
docker inspect helloSinatra | grep IP
docker logs helloSinatra
docker stop helloSinatra
docker rm helloSinatra

curl localhost:8080/
curl localhost:8080/now
curl {container IP}:8080/
curl {container IP}:8080/now



----

